In [3]:
import tensorflow as tf

In [5]:
with tf.compat.v1.Session() as sess:
    A = tf.constant([[1,2,3],[4,5,6]])
    B = tf.constant([[0,0],[1,0],[0,1]])  

In [8]:
  resultado = tf.matmul(A,B)
    

In [9]:
print(tf.Session().run(resultado))

[[2 3]
 [5 6]]


In [12]:
x=tf.constant([3,4,5])

In [13]:
print(tf.Session().run(x))

[3 4 5]


In [15]:
print(x.shape)

(3,)


In [16]:
x=tf.expand_dims(x,1)

In [17]:
print(x.shape)

(3, 1)


In [18]:
resultado2=tf.matmul(A,x)

In [20]:
print(tf.Session().run(resultado2))

[[26]
 [62]]
